version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./sample.sql:/docker-entrypoint-initdb.d/sample.sql

  adminer:
    image: adminer
    container_name: mysql_adminer
    restart: unless-stopped
    ports:
      - "8080:8080"

volumes:
  mysql_data:
    driver: local
